const words = [
    "spiceny", "skurveny", "kokotsky", "prijebany", "idiotsky",
    "pripiceny", "skurvenko", "rozjebanko", "najebany", "buzerantsky",
    "idiotsky", "pro-izraelsky", "retard", "queer-geno",
    "imbecilny", "", "kyjovsky", "dementny", "imbecilko",
    "a este", "najebanec", "pripic", "zajeb", "rododendronko",
    "skurvenisko", "raz kokot, navzdy kokotisko", "furt skurvenisko", "holobriadok",
  "holopusk",
  "mladý vrabec",
  "papľuch",
  "sopliak",
  "O chalanoch",
  "starý blázon",
  "starý caban",
  "starý cap",
  "starý corgoň",
  "starý čert",
  "starý črep",
  "starý hriech",
  "starý hriešnik",
  "starý hrniec",
  "starý kôň",
  "starý koridoň",
  "starý Kubo",
  "starý pes",
  "starý somár",
  "starý vlk",
  "starý vrabec",
  "starigáň",
  "Čiastočne o chalanoch",
  "čiastočne o dospelých i starých",
  "vyčíňajúcich detinské kúsky",
  "stará baba",
  "stará devla",
  "stará drmľa",
  "stará grešľa",
  "stará hrkľa",
  "stará kobza",
  "stará koza",
  "stará krava",
  "stará krkoška",
  "stará mrkva",
  "stará mršina",
  "stará striga",
  "stará škrabňa",
  "smrtka",
  "stariga",
  "Staré čuridlo",
  "staré hebedo",
  "staré hniezdo",
  "staré nemehlo",
  "staré rešeto",
  "staré trdlo", "skučko",
  "skuhroš",
  "skupáň",
  "skývražník",
  "škrvačník",
  "tlčibabka",
  "úžerník",
  "žgrliak", "lanko",
  "mamľas",
  "motoch",
  "motovidlo",
  "mumaj",
  "mumák",
  "našialistý",
  "netrebný",
  "osol",
  "pochabec",
  "pochábeľ",
  "pletkár",
  "pletniak",
  "sadlakurka",
  "somár",
  "sprosták",
  "sprostina", "kokot", "geňo", "piča", "kurva", "retardko", "a a a ", " kriste pane daj mi sekundu...", "a dokonca aj ", "pritom este si aj", 
];

function generateWords() {
    const wordCount = document.getElementById('wordCount').value;
    let generatedWords = [];

    for (let i = 0; i < wordCount; i++) {
        const randomIndex = Math.floor(Math.random() * words.length);
        generatedWords.push(words[randomIndex]);
    }

    const sentence = `ty si ${generatedWords.join(', ')} ?`;
    document.getElementById('wordOutput').innerText = sentence;
}
